sudo: false

language: node_js
node_js:
  - 10
  - 8

cache:
  directories:
    - node_modules

branches:
  only:
    - master

deploy:
  provider: heroku
  app: front-view
  api_key:
    secure: $HEROKU_SECURE
