export const ADD_FLASH_MESSAGE = '[MESSAGE] ADD';
export const DELETE_FLASH_MESSAGE = '[MESSAGE] DELETE';
export const DELETE_FLASH_MESSAGES = '[MESSAGE] DELETE_ALL';

export const USER_SIGNUP = '[USER] SIGNUP';
export const SET_CURRENT_USER = '[USER] SET';
export const CLEANUP_CURRENT_USER = '[USER] CLEAN';
export const USER_GET = '[USER] GET';

export const QUESTIONS_ADD = '[QUESTIONS] ADD';
export const QUESTIONS_GET = '[QUESTIONS] GET';
export const QUESTION_ADD = '[QUESTION] ADD';
export const QUESTION_EDIT = '[QUESTION] EDIT';
export const QUESTION_GET = '[QUESTION] GET';
export const QUESTION_REMOVE = '[QUESTION] REMOVE';
export const FILTER_QUESTIONS = '[QUESTIONS] FILTER';