export const ADD_FLASH_MESSAGE = '[MESSAGE] ADD';
export const DELETE_FLASH_MESSAGE = '[MESSAGE] DELETE';
export const DELETE_FLASH_MESSAGES = '[MESSAGE] DELETE_ALL';

export const USER_SIGNUP = '[USER] SIGNUP';
export const SET_CURRENT_USER = '[USER] SET_CURRENT_USER';
export const USER_GOT = '[USER] GOT';