export const ADD_FLASH_MESSAGE = '[MESSAGE] ADD';
export const DELETE_FLASH_MESSAGE = '[MESSAGE] DELETE';
export const DELETE_FLASH_MESSAGES = '[MESSAGE] DELETE_ALL';

export const USER_SIGNUP = '[USER] SIGNUP';
export const SET_CURRENT_USER = '[USER] SET';
export const CLEANUP_CURRENT_USER = '[USER] CLEAN';
export const USER_GET = '[USER] GET';

export const ADD_QUESTIONS = '[QUESTIONS] ADD_ALL';
export const FILTER_QUESTIONS = '[QUESTIONS] FILTER';
export const GET_QUESTIONS = '[QUESTIONS] GET_ALL';
export const QUESTION_ADDED = '[QUESTION] ADDED';
export const QUESTION_UPDATED = '[QUESTION] UPDATED';
export const QUESTION_GOT = '[QUESTION] GOT';
export const REMOVE_QUESTION = '[QUESTION] REMOVE';
export const EDIT_QUESTION = '[QUESTION] EDIT';